- name: Download splunk universal forwarder
  # Login requirements from splunk website might break this
  win_get_url:
    url: 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=windows&version=7.0.1&product=universalforwarder&filename=splunkforwarder-7.0.1-2b5b15c4ee89-x64-release.msi&wget=true'
    dest: C:\splunkfwd.msi
    force: no

# MSI file with win_package      
- name: Install splunk universal forwarder
  win_package:
    path: C:\splunkfwd.msi
    arguments: AGREETOLICENSE=Yes /qn /norestart
    state: present

- name: Remove splunk universal forwarder
  win_package:
    path: C:\splunkfwd.msi
    state: absent
