- name: insert/update "THP" configuration block in /etc/rc.local
  blockinfile:
    path: /etc/rc.local
    block: |
        if [ -d /sys/kernel/mm/transparent_hugepage ]
        then
          thp_path=/sys/kernel/mm/transparent_hugepage
        elif [ -d /sys/kernel/mm/redhat_transparent_hugepage ]
        then
          thp_path=/sys/kernel/mm/redhat_transparent_hugepage
        else
          return 0
        fi
        
        echo 'never' > ${thp_path}/enabled
        echo 'never' > ${thp_path}/defrag
    state: present
  become_user: root
  become: yes
