- name: Download splunk forwarder
  # Login requirements from splunk website might break this
  #
  get_url:
    # tgz version (maybe consolidate on this download)
    url: 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.0.1&product=universalforwarder&filename=splunkforwarder-7.0.1-2b5b15c4ee89-Linux-x86_64.tgz&wget=true'
    dest: /tmp/splunkfwd.tgz
    force: no

- name: Install splunk forwarder
    unarchive:
    src: /tmp/splunkfwd.tgz
    dest: /opt/splunkforwarder
    remote_src: yes 
