- set_fact:
    deploy_server: 127.0.0.1:8089

- name: Download splunk forwarder
  # Login requirements from splunk website might break this
  #
  get_url:
    url: 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.0.1&product=universalforwarder&filename=splunkforwarder-7.0.1-2b5b15c4ee89-Linux-x86_64.tgz&wget=true'
    dest: /tmp/splunkfwd.tgz
    force: no

- name: Install splunk forwarder
  unarchive:
    src: /tmp/splunkfwd.tgz
    dest: /opt
    remote_src: yes 
    creates: /opt/splunkforwarder/splunkforwarder-7.0.1-2b5b15c4ee89-linux-x86_64-manifest
  register: extracted

- name: Enable boot start
  command: /opt/splunkforwarder/bin/splunk enable boot-start --accept-license
  become_user: root
  become: yes  
  when: extracted.changed

- name: Ensure splunk permissions
  file:
    path: /opt/splunkforwarder
    owner: splunk
    group: splunk
    recurse: yes
    state: directory
  become_user: root
  become: yes
  when: extracted.changed

- name: Connect to Deployment Server
  command: /opt/splunkforwarder/bin/splunk set deploy-poll {{ deploy_server }}
  when: extracted.changed

- name: Start forwarder
  command: /opt/splunkforwarder/bin/splunk start
  when: extracted.changed
