- name: Download splunk 
  # Login requirements from splunk website might break this
  #
  get_url:
    #url: 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.0.1&product=splunk&filename=splunk-7.0.1-2b5b15c4ee89-Linux-x86_64.tgz&wget=true'
    url: 'https://www.splunk.com/bin/splunk/DownloadActivityServlet?architecture=x86_64&platform=linux&version=7.0.2&product=splunk&filename=splunk-7.0.2-03bbabbd5c0f-Linux-x86_64.tgz&wget=true'
    dest: /tmp/splunk.tgz
    force: no

- name: Extract splunk
  unarchive:
    src: /tmp/splunk.tgz
    dest: /opt
    remote_src: yes
#    owner: splunk
#    group: splunk
