- name: Set correct nologin path
  set_fact: 
    nolog_path: "{{ '/usr/sbin/nologin' if ansible_os_family == 'Debian' else '/sbin/nologin' }}"

- name: Add splunk group
  group:
    name: splunk
    state: present

- name: Add splunk user
  user:
    name: splunk
    state: present
    createhome: yes
    home: /opt/splunk
    shell: "{{ nolog_path }}"
